### ISSUE TITLE
 Failed to download R package named gprofilet2

### ISSUE THREAD

**Issue by Zhangmochen-zmc** [abodein/netOmics-case-studies#2]
I cannot find the R package named gprofilet2 in bioconductor or github. Would you like to send the download comand like remotes::install_github() to users? Thanks!

**Comment by Zhangmochen-zmc** [comment]
maybe the package name is gprofiler2? I find this package in the cran.r-project.org

**Comment by abodein** [comment]
Hi,

Yes it is
https://cran.r-project.org/web/packages/gprofiler2/index.html

Le jeu. 2 mars 2023 à 20:25, Zhang Mochen ***@***.***> a
écrit :
